/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type CreateProductInput = {
  title: string,
  description?: string | null,
};

export type Product = {
  __typename: "Product",
  id: string,
  userId: string,
  title: string,
  description?: string | null,
  feedbacks:  Array<Feedback >,
};

export type Feedback = {
  __typename: "Feedback",
  id: string,
  userId: string,
  productId: string,
  title: string,
  feedbackCategoryId: string,
  feedbackStatusId: string,
  details?: string | null,
  comments:  Array<FeedbackComment >,
  product: Product,
  feedbackCategory: FeedbackCategory,
  feedbackStatus: FeedbackStatus,
  upvotes:  Array<Upvote >,
};

export type FeedbackComment = {
  __typename: "FeedbackComment",
  id: string,
  userId: string,
  feedbackId: string,
  comment: string,
  replies:  Array<FeedbackCommentReply >,
  feedback: Feedback,
};

export type FeedbackCommentReply = {
  __typename: "FeedbackCommentReply",
  id: string,
  userId: string,
  feedbackCommentId: string,
  taggedUserId?: string | null,
  comment: string,
  feedbackComment: FeedbackComment,
};

export type FeedbackCategory = {
  __typename: "FeedbackCategory",
  id: string,
  name: string,
  feedbacks:  Array<Feedback >,
};

export type FeedbackStatus = {
  __typename: "FeedbackStatus",
  id: string,
  name: string,
  description?: string | null,
  feedbacks:  Array<Feedback >,
};

export type Upvote = {
  __typename: "Upvote",
  id: string,
  userId: string,
  feedbackId: string,
  feedback: Feedback,
};

export type CreateFeedbackInput = {
  productId: string,
  title: string,
  feedbackCategoryId: string,
  feedbackStatusId: string,
  details?: string | null,
};

export type CreateFeedbackStatusInput = {
  name: string,
  description?: string | null,
};

export type CreateFeedbackCategoryInput = {
  name: string,
  description?: string | null,
};

export type CreateFeedbackCommentInput = {
  feedbackId: string,
  comment: string,
};

export type CreateFeedbackCommentReplyInput = {
  feedbackCommentId: string,
  taggedUserId?: string | null,
  comment: string,
};

export type CreateFeedbackUpvoteInput = {
  feedbackId: string,
};

export type DeleteFeedbackUpvoteInput = {
  feedbackId: string,
};

export type UserInformationInput = {
  userId: string,
};

export type UserInformation = {
  __typename: "UserInformation",
  userId: string,
  email: string,
};

export type FeedbackByProductIdInput = {
  productId: string,
};

export type CreateProductMutationVariables = {
  data?: CreateProductInput | null,
};

export type CreateProductMutation = {
  createProduct:  {
    __typename: "Product",
    id: string,
    userId: string,
    title: string,
    description?: string | null,
    feedbacks:  Array< {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    } >,
  },
};

export type CreateFeedbackMutationVariables = {
  data?: CreateFeedbackInput | null,
};

export type CreateFeedbackMutation = {
  createFeedback:  {
    __typename: "Feedback",
    id: string,
    userId: string,
    productId: string,
    title: string,
    feedbackCategoryId: string,
    feedbackStatusId: string,
    details?: string | null,
    comments:  Array< {
      __typename: "FeedbackComment",
      id: string,
      userId: string,
      feedbackId: string,
      comment: string,
      replies:  Array< {
        __typename: "FeedbackCommentReply",
        id: string,
        userId: string,
        feedbackCommentId: string,
        taggedUserId?: string | null,
        comment: string,
        feedbackComment:  {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        },
      } >,
      feedback:  {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      },
    } >,
    product:  {
      __typename: "Product",
      id: string,
      userId: string,
      title: string,
      description?: string | null,
      feedbacks:  Array< {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      } >,
    },
    feedbackCategory:  {
      __typename: "FeedbackCategory",
      id: string,
      name: string,
      feedbacks:  Array< {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      } >,
    },
    feedbackStatus:  {
      __typename: "FeedbackStatus",
      id: string,
      name: string,
      description?: string | null,
      feedbacks:  Array< {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      } >,
    },
    upvotes:  Array< {
      __typename: "Upvote",
      id: string,
      userId: string,
      feedbackId: string,
      feedback:  {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      },
    } >,
  },
};

export type CreateFeedbackStatusMutationVariables = {
  data?: CreateFeedbackStatusInput | null,
};

export type CreateFeedbackStatusMutation = {
  createFeedbackStatus:  {
    __typename: "FeedbackStatus",
    id: string,
    name: string,
    description?: string | null,
    feedbacks:  Array< {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    } >,
  },
};

export type CreateFeedbackCategoryMutationVariables = {
  data?: CreateFeedbackCategoryInput | null,
};

export type CreateFeedbackCategoryMutation = {
  createFeedbackCategory:  {
    __typename: "FeedbackCategory",
    id: string,
    name: string,
    feedbacks:  Array< {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    } >,
  },
};

export type CreateFeedbackCommentMutationVariables = {
  data?: CreateFeedbackCommentInput | null,
};

export type CreateFeedbackCommentMutation = {
  createFeedbackComment:  {
    __typename: "FeedbackComment",
    id: string,
    userId: string,
    feedbackId: string,
    comment: string,
    replies:  Array< {
      __typename: "FeedbackCommentReply",
      id: string,
      userId: string,
      feedbackCommentId: string,
      taggedUserId?: string | null,
      comment: string,
      feedbackComment:  {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      },
    } >,
    feedback:  {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    },
  },
};

export type CreateFeedbackCommentReplyMutationVariables = {
  data?: CreateFeedbackCommentReplyInput | null,
};

export type CreateFeedbackCommentReplyMutation = {
  createFeedbackCommentReply:  {
    __typename: "FeedbackCommentReply",
    id: string,
    userId: string,
    feedbackCommentId: string,
    taggedUserId?: string | null,
    comment: string,
    feedbackComment:  {
      __typename: "FeedbackComment",
      id: string,
      userId: string,
      feedbackId: string,
      comment: string,
      replies:  Array< {
        __typename: "FeedbackCommentReply",
        id: string,
        userId: string,
        feedbackCommentId: string,
        taggedUserId?: string | null,
        comment: string,
        feedbackComment:  {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        },
      } >,
      feedback:  {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      },
    },
  },
};

export type CreateFeedbackUpvoteMutationVariables = {
  data?: CreateFeedbackUpvoteInput | null,
};

export type CreateFeedbackUpvoteMutation = {
  createFeedbackUpvote:  {
    __typename: "Upvote",
    id: string,
    userId: string,
    feedbackId: string,
    feedback:  {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    },
  },
};

export type DeleteFeedbackUpvoteMutationVariables = {
  data?: DeleteFeedbackUpvoteInput | null,
};

export type DeleteFeedbackUpvoteMutation = {
  deleteFeedbackUpvote:  {
    __typename: "Upvote",
    id: string,
    userId: string,
    feedbackId: string,
    feedback:  {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    },
  },
};

export type GetUserInformationByIdQueryVariables = {
  data?: UserInformationInput | null,
};

export type GetUserInformationByIdQuery = {
  getUserInformationById:  {
    __typename: "UserInformation",
    userId: string,
    email: string,
  },
};

export type GetAllProductsQueryVariables = {
};

export type GetAllProductsQuery = {
  getAllProducts:  Array< {
    __typename: "Product",
    id: string,
    userId: string,
    title: string,
    description?: string | null,
    feedbacks:  Array< {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    } >,
  } >,
};

export type GetAllFeedbacksByProductIdQueryVariables = {
  data?: FeedbackByProductIdInput | null,
};

export type GetAllFeedbacksByProductIdQuery = {
  getAllFeedbacksByProductId:  Array< {
    __typename: "Feedback",
    id: string,
    userId: string,
    productId: string,
    title: string,
    feedbackCategoryId: string,
    feedbackStatusId: string,
    details?: string | null,
    comments:  Array< {
      __typename: "FeedbackComment",
      id: string,
      userId: string,
      feedbackId: string,
      comment: string,
      replies:  Array< {
        __typename: "FeedbackCommentReply",
        id: string,
        userId: string,
        feedbackCommentId: string,
        taggedUserId?: string | null,
        comment: string,
        feedbackComment:  {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        },
      } >,
      feedback:  {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      },
    } >,
    product:  {
      __typename: "Product",
      id: string,
      userId: string,
      title: string,
      description?: string | null,
      feedbacks:  Array< {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      } >,
    },
    feedbackCategory:  {
      __typename: "FeedbackCategory",
      id: string,
      name: string,
      feedbacks:  Array< {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      } >,
    },
    feedbackStatus:  {
      __typename: "FeedbackStatus",
      id: string,
      name: string,
      description?: string | null,
      feedbacks:  Array< {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      } >,
    },
    upvotes:  Array< {
      __typename: "Upvote",
      id: string,
      userId: string,
      feedbackId: string,
      feedback:  {
        __typename: "Feedback",
        id: string,
        userId: string,
        productId: string,
        title: string,
        feedbackCategoryId: string,
        feedbackStatusId: string,
        details?: string | null,
        comments:  Array< {
          __typename: "FeedbackComment",
          id: string,
          userId: string,
          feedbackId: string,
          comment: string,
        } >,
        product:  {
          __typename: "Product",
          id: string,
          userId: string,
          title: string,
          description?: string | null,
        },
        feedbackCategory:  {
          __typename: "FeedbackCategory",
          id: string,
          name: string,
        },
        feedbackStatus:  {
          __typename: "FeedbackStatus",
          id: string,
          name: string,
          description?: string | null,
        },
        upvotes:  Array< {
          __typename: "Upvote",
          id: string,
          userId: string,
          feedbackId: string,
        } >,
      },
    } >,
  } >,
};

export type GetAllFeedbackStatusesQueryVariables = {
};

export type GetAllFeedbackStatusesQuery = {
  getAllFeedbackStatuses:  Array< {
    __typename: "FeedbackStatus",
    id: string,
    name: string,
    description?: string | null,
    feedbacks:  Array< {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    } >,
  } >,
};

export type GetAllFeedbackCategoriesQueryVariables = {
};

export type GetAllFeedbackCategoriesQuery = {
  getAllFeedbackCategories:  Array< {
    __typename: "FeedbackCategory",
    id: string,
    name: string,
    feedbacks:  Array< {
      __typename: "Feedback",
      id: string,
      userId: string,
      productId: string,
      title: string,
      feedbackCategoryId: string,
      feedbackStatusId: string,
      details?: string | null,
      comments:  Array< {
        __typename: "FeedbackComment",
        id: string,
        userId: string,
        feedbackId: string,
        comment: string,
        replies:  Array< {
          __typename: "FeedbackCommentReply",
          id: string,
          userId: string,
          feedbackCommentId: string,
          taggedUserId?: string | null,
          comment: string,
        } >,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
      product:  {
        __typename: "Product",
        id: string,
        userId: string,
        title: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackCategory:  {
        __typename: "FeedbackCategory",
        id: string,
        name: string,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      feedbackStatus:  {
        __typename: "FeedbackStatus",
        id: string,
        name: string,
        description?: string | null,
        feedbacks:  Array< {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        } >,
      },
      upvotes:  Array< {
        __typename: "Upvote",
        id: string,
        userId: string,
        feedbackId: string,
        feedback:  {
          __typename: "Feedback",
          id: string,
          userId: string,
          productId: string,
          title: string,
          feedbackCategoryId: string,
          feedbackStatusId: string,
          details?: string | null,
        },
      } >,
    } >,
  } >,
};
